# Exported from Render on 2026-07-21T18:16:34Z
version: "1"
services:
- type: web
  name: textune-api
  runtime: python
  repo: https://github.com/Fres02/thermotune-task
  plan: free
  envVars:
  - key: GEMINI_API_KEY
    sync: false
  - key: CORS_ORIGINS
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  autoDeployTrigger: commit
  rootDir: apps/api
